name: CI

on:
  push:
    branches: [ dockerfiles ]
  pull_request:
    branches: [ dockerfiles ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Docker-compose up -d
        run: docker-compose up -d
        
      - name: Test serveur up
        run: curl http://localhost:3100/
