name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - shell: pwsh
        env:
          API_KEY_TRANSLATE: ${{ secrets.API_KEY_TRANSLATE }}
        run: |
            echo "$API_KEY_TRANSLATE"

      - name: Serveur - npm install + npm test
        run: |
          cd serveur
          npm install
          npm test

      - name: Docker-compose up -d
        run: docker-compose up -d
        
      - name: Test serveur up
        run: curl http://localhost:3100/
