name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Serveur - npm install + npm test
        run: |
          cd serveur
          npm install
          npm test

      - name: Docker-compose up -d
        run: docker-compose up -d
        
      - name: Test serveur up
        run: curl http://localhost:3100/
