name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Docker-compose up -d
        run: docker-compose up -d

      - name: Docker-compose start
        run: docker-compose start

      - name: Test serveur up
        run: curl http://localhost:3100/
        
      - name: Test angular up
        run: curl http://localhost:4200/
        
      - name: Test mongo up
        run: curl http://localhost:27017/

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - Creation
          draft: false
          prerelease: false
